### ISSUE TITLE
Minecraft 1.12-pre2

### ISSUE THREAD

**Issue by ghost** [DavideBlade/AntiWorldDownloader#1]
Hey

On latest version (Pre version released from Spigot) I'm getting http://paste.yu8.me/?430b89438bbb74b1#UF09M5U7UAuOom0ICPE5/mlVFI4nVNZKNMgtBm6/PxY=

Just giving you a heads up before 1.12 is released

**Comment by DavideBlade** [comment]
As soon as a stable release is released, I will update the plugin. Currently, spigot releases an update every 3 days and is impossible for me update the plugin at the same pace. Is there a particular reason why you want to try it in advance?

**Comment by ghost** [comment]
Always good to be one step more ahead of things.

**Comment by DavideBlade** [comment]
I agree, but however, unfortunately, as I said I can not update the plugin every 3 days with the new Spigot version.

If it can be useful, there won't be (probably) changes in the next version for Minecraft 1.12.
