### ISSUE TITLE
Spanish translation for Anti World Downloader

### ISSUE THREAD

**Issue by AlexCraft855** [DavideBlade/AntiWorldDownloader#12]
Hi,
I attach you the Spanish translation for Anti World Downloader plugin for you to add them. 
Don't forget to put the format in .yml, I have put it in .txt, because if not, GitHub will not let me upload it.
Thank you for read,
Kind regards,
Alex Craft. @
[messages_es.yml.txt](https://github.com/user-attachments/files/16515881/messages_es.yml.txt)

**Comment by DavideBlade** [comment]
Thank you! I will publish it in the next version (2.7.1.2) after validation.

What is your account on Spigot (if you have one)?
