### ISSUE TITLE
i make a chinese messages to you

### ISSUE THREAD

**Issue by MCFurina** [DavideBlade/AntiWorldDownloader#5]
[messages_zhcn.yml.txt](https://github.com/DavideBlade/AntiWorldDownloader/files/14395411/messages_zhcn.yml.txt)
Please remove .txt when using

**Comment by DavideBlade** [comment]
Translation added in version [2.6.8](https://github.com/DavideBlade/AntiWorldDownloader/commit/d661e4afd5cf3ef933584b176b937c04c5c918f5) (https://github.com/DavideBlade/AntiWorldDownloader/commit/439389e2bcf870ce3305c63d1d1eee39a4e2b048). Thanks!
