### ISSUE TITLE
World Download Issue

### ISSUE THREAD

**Issue by MyoWalE** [DavideBlade/AntiWorldDownloader#6]
I tried to block download using AWD, but it can't block world download by [WorldDownloader](https://github.com/mircokroon/minecraft-world-downloader). If you have time, please check it later
Thank you :)

**Comment by DavideBlade** [comment]
Hello, it has already been reported to me some time ago. I contacted the developer but he has no plans to make any changes to the mod, so unfortunately nothing can be done about it :disappointed:
