### ISSUE TITLE
Where should i put this for a velocity network? 

### ISSUE THREAD

**Issue by HiddeNBinary** [DavideBlade/AntiWorldDownloader#8]
Hello!
Where should i put this plugin in a velocity network?

In velocity server's plugin folder or every server's plugin folder in the velocity network?

**Comment by DavideBlade** [comment]
It must be put on the proxy server (the one using Velocity, not the server running Spigot/PaperSpigot etc.).

**Comment by HiddeNBinary** [comment]
> It must be put on the proxy server (the one using Velocity, not the server running Spigot/PaperSpigot etc.).

Understood, Thanks!
